export const messageData = [
    {
        id: 1,
        name: 'Belay Birhanu',
        message: 'Hi! are you fine bro',
        createdAt: '12/12/12',
        sender: 'mine',
    }, {
        id: 2,
        name: 'Abebe Kebede',
        message: 'Hi! are you fine broHi! are you fine broHi! are you fine broHi! are you fine bro',
        createdAt: '12/12/12',
        sender: 'other',
    },
    {
        id: 3,
        name: 'Belay Haile',
        message: 'Hi! aHi! are you fiHi! are you fine brone broHi! Hi! are you fine broare you fine brore you fine bro',
        createdAt: '12/12/12',
        sender: 'mine',
    },
    {
        id: 4,
        name: 'Moges Haylu',
        message: 'Hi! are you fine bro',
        createdAt: '12/12/12',
        sender: 'other',
    }, {
        id: 5,
        name: 'Belay Birhanu',
        message: 'Hi! are you fine bro',
        createdAt: '12/12/12',
        sender: 'mine',
    }, {
        id: 6,
        name: 'Abebe Kebede',
        message: 'Hi! are you fine broHi! are you fine broHi! are you fine broHi! are you fine bro',
        createdAt: '12/12/12',
        sender: 'other',
    },
    {
        id: 7,
        name: 'Belay Haile',
        message: 'Hi! aHi! are you fiHi! are you fine brone broHi! Hi! are you fine broare you fine brore you fine bro',
        createdAt: '12/12/12',
        sender: 'mine',
    },
    {
        id: 8,
        name: 'Moges Haylu',
        message: 'Hi! are you fine bro',
        createdAt: '12/12/12',
        sender: 'other',
    },
    {
        id: 9,
        name: 'Belay Birhanu',
        message: 'Hi! are you fine bro',
        createdAt: '12/12/12',
        sender: 'mine',
    },
    {
        id: 10,
        name: 'Belay Birhanu',
        message: 'Hi! are you fine bro',
        createdAt: '12/12/12',
        sender: 'other',
    },
]