export const userData = [
    {
        id: 1,
        name: 'Belay Birhanu',
        username: 'user1',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 2,
        name: 'Abebe Kebede',
        username: 'admin2',
        password: '1234a',
        avatar: require('../../assets/background.png'),
        newMessage: 'Hey there!',
    }, {
        id: 3,
        name: 'Belay Birhanu',
        username: 'admin3',
        password: '1234a',
        avatar: require('../../assets/belay.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 4,
        name: 'Abebe Kebede',
        username: 'admin4',
        password: '1234a',
        avatar: require('../../assets/belay.png'),
        newMessage: 'Hey there!',
    }, {
        id: 5,
        name: 'Belay Birhanu',
        username: 'admin5',
        password: '1234a',
        avatar: require('../../assets/background.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 6,
        name: 'Abebe Kebede',
        username: 'user1',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hey there!',
    }, {
        id: 7,
        name: 'Belay Birhanu',
        username: 'user2',
        password: '1234a',
        avatar: require('../../assets/light.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 8,
        name: 'Abebe Kebede',
        username: 'user3',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hey there!',
    }, {
        id: 9,
        name: 'Belay Birhanu',
        username: 'user4',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 10,
        name: 'Abebe Kebede',
        username: 'user5',
        password: '1234a',
        avatar: require('../../assets/belay.png'),
        newMessage: 'Hey there!',
    }, {
        id: 11,
        name: 'Belay Birhanu',
        username: 'user6',
        password: '1234a',
        avatar: require('../../assets/background.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 12,
        name: 'Balcha Debebe',
        username: 'user7',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hey there!',
    }, {
        id: 13,
        name: 'Belay Birhanu',
        username: 'user8',
        password: '1234a',
        avatar: require('../../assets/belay.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 14,
        name: 'Balcha Debebe',
        username: 'user9',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hey there!',
    }, {
        id: 15,
        name: 'Belay Birhanu',
        username: 'user10',
        password: '1234a',
        avatar: require('../../assets/belay.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 16,
        name: 'Balcha Debebe',
        username: 'user11',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hey there!',
    }, {
        id: 17,
        name: 'Belay Birhanu',
        username: 'user12',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 18,
        name: 'Balcha Debebe',
        username: 'user13',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hey there!',
    }, {
        id: 19,
        name: 'Belay Birhanu',
        username: 'user14',
        password: '1234a',
        avatar: require('../../assets/belay.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 20,
        name: 'Balcha Debebe',
        username: 'user15',
        password: '1234a',
        avatar: require('../../assets/light.png'),
        newMessage: 'Hey there!',
    }, {
        id: 21,
        name: 'Belay Birhanu',
        username: 'user16',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 22,
        name: 'Balcha Debebe',
        username: 'user17',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hey there!',
    }, {
        id: 23,
        name: 'Belay Birhanu',
        username: 'user18',
        password: '1234a',
        avatar: require('../../assets/belay.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 24,
        name: 'Balcha Debebe',
        username: 'user19',
        password: '1234a',
        avatar: require('../../assets/background.png'),
        newMessage: 'Hey there!',
    }, {
        id: 25,
        name: 'Belay Birhanu',
        username: 'user20',
        password: '1234a',
        avatar: require('../../assets/belay.png'),
        newMessage: 'Hello, how are you?',
    },
    {
        id: 26,
        name: 'Balcha Debebe',
        username: 'user21',
        password: '1234a',
        avatar: require('../../assets/profile_bg.png'),
        newMessage: 'Hey there!',
    },
];